### ISSUE TITLE
Cartridge not read properly

### ISSUE THREAD

**Issue by Matthew8183** [edo9300/ndsi-savedumper#1]
it says cartdige not read properly please reinsert it, however ive tried with several different ds games that are tested and working. it must be something with the program

**Comment by Epicpkmn11** [comment]
Maybe try using [GodMode9i](https://github.com/DS-Homebrew/GodMode9i/releases) ([nightly](https://github.com/TWLBot/Builds/raw/master/extras/GodMode9i.7z)) instead, it has a few fixes related to save files which aren't in this. (Probably best to use the nightly build as it has a fix related to save dumping / restoring that isn't in the latest release)

If there's interest in porting those fixes back into this (should be easy as GM9i's save code is based on this) the relevant PR's are DS-Homebrew/GodMode9i#79, DS-Homebrew/GodMode9i#94 (improvement on 79), and DS-Homebrew/GodMode9i#88.

---

Edit: Oh also make sure you have Unlaunch installed, DSiWarehax such as Memory Pit don't have access to Slot-1
